# Generated by Django 5.2.6 on 2025-09-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('ball', 'Ball'), ('shoes', 'Shoes'), ('gloves', 'Gloves'), ('gear', 'Protective Gear'), ('training', 'Training Equipment'), ('accessories', 'Accessories')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
